### ISSUE TITLE
Auto Rigging not supported

### ISSUE THREAD

**Issue by robosoup2** [thnewlands/3D-Texture-Brush-for-Mudbun#1]
no errors, but any Verts that would be skinned to a 3Dtex brush bone all get sucked into the center point of the model instead

**Comment by thnewlands** [comment]
Fixed here! I didn't realize I was missing a section in the compute data for the custom brush script.

https://github.com/thnewlands/3D-Texture-Brush-for-Mudbun/commit/890b72d990253ff9d81e88358aa7f6735f4320db
