### ISSUE TITLE
Breaks in build or when leaving Play mode if SDFBrush isn't being used

### ISSUE THREAD

**Issue by robosoup2** [thnewlands/3D-Texture-Brush-for-Mudbun#3]
when starting my build or leaving play mode, if you have no SDFTextureSolidBrushes in the scene, then all mudRenderers will throw these 2 errors and won't render anything.
in editor, you can fix the error by adding an SDFTextureSolidBrush primitive to any mudrenderer. then all the mud renderers in the scene will start working again, and you can safely delete the SDFbrush. 

![image](https://github.com/thnewlands/3D-Texture-Brush-for-Mudbun/assets/50124081/3010aa52-7186-4976-994a-a84d05d481c8)
![image](https://github.com/thnewlands/3D-Texture-Brush-for-Mudbun/assets/50124081/3a712c7f-197f-48f6-8336-04773c27f021)

**Comment by thnewlands** [comment]
Gah I took out a hack for solving this when I published this repository. I made a singleton collection that mudrenderers would initialize onenable. I wasn't happy with it so I stripped things down.

My hope is to solve this ultimately with compiler defines in the shadercode. I'm having trouble figuring out how to get them working properly. This one is a high priority for me.

**Comment by thnewlands** [comment]
Not my proudest moment but I have a fix here for keeping the texture data always accessible to the compute shader until a better solution appears: 
https://github.com/thnewlands/3D-Texture-Brush-for-Mudbun/commit/a638042faa789eb922ea11a76396c7e72d55afd0
